import { z } from "zod";

import { AppError } from "../errors.js";
import { logger } from "../logger.js";
const SECTION_TITLES = {
  summary: "Learn this concept",
  explanation: "Simple explanation",
  key_points: "Key points",
  example: "Example",
  analogy: "Analogy",
  follow_ups: "Follow-up questions",
};
export const RESPONSE_DISCLAIMER =
  "NoviLearn answers are generated by AI and may not always be perfectly accurate. Please double-check important facts.";
const MAX_LIST_ITEMS = 6;
const MIN_VISUAL_NODES = 2;
const MAX_VISUAL_NODES = 6;
const visualNodeSchema = z.object({
  label: z.string(),
  details: z.string().optional(),
});
const visualEdgeSchema = z.object({
  from: z.number().int().nonnegative(),
  to: z.number().int().nonnegative(),
  label: z.string().optional(),
});
const visualRepresentationSchema = z.object({
  type: z.enum(["flow", "steps", "chain"]),
  title: z.string().optional(),
  nodes: z.array(visualNodeSchema),
  edges: z.array(visualEdgeSchema).optional(),
});
const providerResponseSchema = z.object({
  summary: z.string().optional(),
  explanation: z.string().optional(),
  keyPoints: z.array(z.string()).optional(),
  example: z.string().optional(),
  analogy: z.string().optional(),
  followUps: z.array(z.string()).optional(),
  relatedConcepts: z.array(z.string()).optional(),
  nextTopics: z.array(z.string()).optional(),
  visualRepresentation: visualRepresentationSchema.optional(),
});
function invalidResponse() {
  return new AppError(
    502,
    "AI_RESPONSE_INVALID",
    "AI Tutor is temporarily unavailable",
  );
}
function cleanString(value) {
  const trimmed = value?.trim() ?? "";
  return trimmed === "" ? null : trimmed;
}
function cleanList(value, maxItems) {
  if (!value) {
    return [];
  }
  return value
    .map((item) => item.trim())
    .filter((item) => item !== "")
    .slice(0, maxItems);
}
function cleanVisual(raw) {
  const nodes = raw.nodes
    .map((node) => ({
      label: cleanString(node.label),
      details: cleanString(node.details),
    }))
    .filter((node) => node.label !== null)
    .slice(0, MAX_VISUAL_NODES);
  if (nodes.length < MIN_VISUAL_NODES) {
    return null;
  }
  const edgeRecords = (raw.edges ?? []).filter(
    (edge) =>
      edge.from !== edge.to &&
      edge.from < nodes.length &&
      edge.to < nodes.length,
  );
  let edges;
  if (edgeRecords.length === 0) {
    edges = nodes.slice(0, -1).map((_node, index) => ({
      from: index,
      to: index + 1,
    }));
  } else {
    edges = edgeRecords.map((edge) => ({
      from: edge.from,
      to: edge.to,
      ...(cleanString(edge.label) !== null
        ? {
            label: cleanString(edge.label),
          }
        : {}),
    }));
  }
  return {
    type: raw.type,
    title: cleanString(raw.title) ?? "How it works",
    nodes: nodes.map((node) => ({
      label: node.label,
      ...(node.details !== null
        ? {
            details: node.details,
          }
        : {}),
    })),
    edges,
  };
}
export function normalizeProviderResponse(question, rawContent) {
  let parsed;
  try {
    parsed = JSON.parse(rawContent);
  } catch {
    logger.error("[ai] response is not valid json");
    throw invalidResponse();
  }
  const result = providerResponseSchema.safeParse(parsed);
  if (!result.success) {
    logger.error("[ai] response does not match expected shape");
    throw invalidResponse();
  }
  const raw = result.data;
  const summary = cleanString(raw.summary);
  if (summary === null) {
    logger.error("[ai] response is missing required summary");
    throw invalidResponse();
  }
  const sections = [
    {
      type: "summary",
      title: SECTION_TITLES.summary,
      content: summary,
    },
  ];
  const explanation = cleanString(raw.explanation);
  if (explanation !== null) {
    sections.push({
      type: "explanation",
      title: SECTION_TITLES.explanation,
      content: explanation,
    });
  }
  const keyPoints = cleanList(raw.keyPoints, MAX_LIST_ITEMS);
  if (keyPoints.length > 0) {
    sections.push({
      type: "key_points",
      title: SECTION_TITLES.key_points,
      items: keyPoints,
    });
  }
  const example = cleanString(raw.example);
  if (example !== null) {
    sections.push({
      type: "example",
      title: SECTION_TITLES.example,
      content: example,
    });
  }
  const analogy = cleanString(raw.analogy);
  if (analogy !== null) {
    sections.push({
      type: "analogy",
      title: SECTION_TITLES.analogy,
      content: analogy,
    });
  }
  const followUps = cleanList(raw.followUps, MAX_LIST_ITEMS);
  if (followUps.length > 0) {
    sections.push({
      type: "follow_ups",
      title: SECTION_TITLES.follow_ups,
      items: followUps,
    });
  }
  const relatedConcepts = cleanList(raw.relatedConcepts, MAX_LIST_ITEMS);
  const nextTopics = cleanList(raw.nextTopics, MAX_LIST_ITEMS);
  const visual =
    raw.visualRepresentation !== undefined
      ? cleanVisual(raw.visualRepresentation)
      : null;
  return {
    question: question.trim(),
    sections,
    ...(relatedConcepts.length > 0
      ? {
          relatedConcepts,
        }
      : {}),
    ...(nextTopics.length > 0
      ? {
          nextLearning: nextTopics,
        }
      : {}),
    ...(visual !== null
      ? {
          visualLearning: visual,
        }
      : {}),
    disclaimer: RESPONSE_DISCLAIMER,
  };
}
